### ISSUE TITLE
[BUG] CIが失敗している

### ISSUE THREAD

**Issue by gpioblink** [AizuGeekDojo/AizuGeekDojo.github.io#96]
## 不具合の詳細

CIに失敗しているようで、サイトが更新されない。

昔成功していたコミットでworkflowを実行しても失敗するので、周辺環境の変化が問題だと思われる。

## 再現方法

masterにコミット(マージ)するか、

https://app.circleci.com/pipelines/github/AizuGeekDojo/NeoWebPage?branch=master

で適切なworkflowを実行する

## 本来の動き

workflowの実行に成功する

## スクリーンショット(可能なら)

![image](https://user-images.githubusercontent.com/38032069/122210193-53de3600-cee0-11eb-85f3-12a65f415df4.png)

**Comment by wancom** [comment]
これは多分`node-sass`パッケージが最新のnodeに対応していないためです。
今`node:latest`イメージを使ってCIが動いていますが古いバージョンのイメージを指定すれば動くと思います。

**Comment by wancom** [comment]
そもそも`node-sass`は非推奨っぽい？
https://qiita.com/n0bisuke/items/123a69ba5940f11404aa

**Comment by wancom** [comment]
もしくは`node-sass`のバージョンを上げられるならあげると最新のnodeも対応しそう
https://www.npmjs.com/package/node-sass

**Comment by gpioblink** [comment]
古いバージョン(node v14)指定ししたら動きました。

とりあえず、これがよさそうなのでプルリク作ります〜

https://github.com/AizuGeekDojo/NeoWebPage/issues/96#issuecomment-862300050

**Comment by gpioblink** [comment]
eslint-loaderももう非推薦らしいから、
こっちもeslint-webpack-pluginにかえときます
(これのせいでnuxtのバージョンが上がらなかった)

https://runebook.dev/ja/docs/webpack/plugins/eslint-webpack-plugin

**Comment by gpioblink** [comment]
なんか`node-ssas`を`ssas`にしたらいろいろ文法エラー出てつらい。。

> 例えば dart-sass は /deep/ のサポートをしていません。

https://blog.mahoroi.com/posts/2019/03/scoped-css-v-deep/
